### POST request to create a patient
POST http://localhost:8080/patients
Content-Type: application/json

{
  "name": "Sam Smith",
  "email": "sam.smith2@mail.com",
  "address": "321 Cherry St, Shelbyville",
  "dateOfBirth": "1995-09-09"
}
###