### PUT request to update a patient
PUT http://localhost:8080/api/patients/9613687a-f102-4a48-9f94-858148446d1d
Content-Type: application/json

{
  "name": "Sam Smith",

  "address": "321 Cherry St, Shelbyville",
  "dateOfBirth": "1995-10-09",
  "email": "sam.smith@mail.com"
}
###